# configs/rat15_srnn.yaml
experiment:
  name: "rat15_tbptt_w40_s10_k3"
  description: "SRNN: DCA(d=8), K=3, TBPTT(24), window 40/stride 10."
  seed: 0

data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: false

model:
  K_states: 3
  latent_dim: 8
  kappa: 3.0              # <-- single value (recommended to start)

dr:
  method: "dca1"
  n_components: 8
  random_state: 0

training:
  num_iters: 2000
  window_size: 40         # <-- your request
  stride: 10              # <-- your request
  tbptt_steps: 24         # <-- NEW: enables truncated BPTT
  batch_size: 256
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2
  ms_per_sample: 1000
  rate_mode: "mean"
  shock_expand_sec: 2.0

initialization:
  warmup_epochs: 400
  lambda_entropy: 1.0e-4
  lambda_usage: 2.0e-2

evaluation:
  prediction_horizons: [10, 20, 30, 40]

rslds_init:
  path: "/content/drive/My Drive/sRNN/Rat15/initialization for srnn/drop_nan_15000i_z_hat_A.npy"
  use_head: 200

