# ===============================
# Experiment configuration: Rat 15 SRNN (100 ms from HDF5)
# ===============================

experiment:
  name: "rat15_100ms_from_h5_tbptt_w40_s10_k3"
  description: "SRNN (DCA-8, K=3), TBPTT=24, window=40/stride=10; FR & shocks from 10 ms HDF5, downsampled to 100 ms."
  seed: 0
  mode: "unsupervised"     # just metadata

# ===============================
# Data parameters
# ===============================
data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"                # <- rSLDS root
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: false      # require the HDF5; no CSV / npy

# ===============================
# Model parameters
# ===============================
model:
  K_states: 3
  latent_dim: 8
  kappa: 6.0
  use_inputs: false       # UNSUPERVISED: ignore u during training, but we still build and save it

# ===============================
# Dimensionality reduction
# ===============================
dr:
  method: "dca1"
  n_components: 8
  random_state: 0

# ===============================
# Training configuration
# ===============================
training:
  num_iters: 15000
  window_size: 40
  stride: 10
  tbptt_steps: 24
  batch_size: 256
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2

  # IMPORTANT:
  # native bin size of the HDF5 is 10 ms → we will downsample to 100 ms *inside* srnn_helper.py
  ms_per_sample: 10      # native bin of HDF5 (10 ms)
  rate_mode: "mean"

  # Footshock input params (used to build binary regressor at 10 ms before downsampling)
  shock_expand_sec: 1.5
  u_scale: 2.0           # meta only

# ===============================
# Initialization & regularization
# ===============================
initialization:
  warmup_epochs: 700
  lambda_entropy: 1.0e-5
  lambda_usage: 2.0e-2

# ===============================
# Evaluation
# ===============================
evaluation:
  prediction_horizons: [10, 20, 30, 40]

# ===============================
# Optional warm-start from rSLDS
# ===============================
rslds_init:
  path: "/content/drive/MyDrive/RSLDS_SRNN/ModelOutputs/BehaviouralModelrSLDS/Rat{rat_id}/behav_rslds_dropNaN_K3_D1_it12000_z_hat.npy"
  use_head: 500

# ===============================
# Small hyperparameter grid (metadata)
# ===============================
search:
  kappa: [4.0, 6.0, 8.0, 10.0]
  lr: [1e-3, 5e-4, 1e-4]


