# ===============================
# Experiment configuration: Rat 15 SRNN (WITH footshock inputs)
# ===============================

experiment:
  name: "rat15_tbptt_w40_s10_k3_footshock"
  description: "SRNN (DCA-8, K=3), TBPTT=24, window=40/stride=10; WITH footshock inputs."
  seed: 0
  mode: "with_inputs"

# ===============================
# Data parameters
# ===============================
data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive_inputs"   # <--- different subset name so folder is different
  h5_optional: false

# ===============================
# Model parameters
# ===============================
model:
  K_states: 3
  latent_dim: 8
  kappa: 6.0
  use_inputs: true              # <--- TURNED ON: use footshock regressor

# ===============================
# Dimensionality reduction
# ===============================
dr:
  method: "dca1"
  n_components: 8
  random_state: 0

# ===============================
# Training configuration
# ===============================
training:
  num_iters: 15000
  window_size: 40
  stride: 10
  tbptt_steps: 24
  batch_size: 256
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2

  # We are using your 100 ms downsampled FR .npy:
  # /content/drive/MyDrive/RSLDS_SRNN/Downsampled-FiringRates/NpxFiringRate_100msBINSRat15.npy
  ms_per_sample: 100
  rate_mode: "mean"

  # Footshock settings (NOW actually used because use_inputs=true)
  shock_expand_sec: 1.5
  u_scale: 2.0   # still just metadata (not used in code), but fine

# ===============================
# Initialization & regularization
# ===============================
initialization:
  warmup_epochs: 700
  lambda_entropy: 1.0e-5
  lambda_usage: 2.0e-2

# ===============================
# Evaluation
# ===============================
evaluation:
  prediction_horizons: [10, 20, 30, 40]

# ===============================
# Optional warm-start from rSLDS
# ===============================
rslds_init:
  path: "/content/drive/MyDrive/RSLDS_SRNN/ModelOutputs/BehaviouralModelrSLDS/Rat{rat_id}/behav_rslds_dropNaN_K3_D1_it12000_z_hat.npy"
  use_head: 500

# ===============================
# Small hyperparameter grid (metadata only)
# ===============================
search:
  kappa: [4.0, 6.0, 8.0, 10.0]
  lr: [1e-3, 5e-4, 1e-4]
