# ===============================
# Experiment configuration: Rat 15 SRNN (100 ms from HDF5)
# ===============================

experiment:
  name: "rat15_100ms_from_h5_tbptt_w200_s20_k3"     # CHANGED
  description: "SRNN (DCA-8, K=3), TBPTT=200, window=200/stride=20; FR & shocks from 10 ms HDF5, downsampled to 100 ms."  # CHANGED
  seed: 0
  mode: "unsupervised"

# ===============================
# Data parameters
# ===============================
data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: false

# ===============================
# Model parameters
# ===============================
model:
  K_states: 3
  latent_dim: 8
  kappa: 7.0                 # you already increased this
  use_inputs: false          # keep unsupervised for now

# ===============================
# Dimensionality reduction
# ===============================
dr:
  method: "dca1"
  n_components: 8
  random_state: 0

# ===============================
# Training configuration
# ===============================
training:
  num_iters: 15000
  window_size: 50           # CHANGED  (≈20 s at 100 ms)
  stride: 15                 # CHANGED  (more overlap than before but fewer windows than stride=10)
  tbptt_steps: 50           # CHANGED  (backprop over full 20 s window)
  batch_size: 32             # CHANGED  (smaller batch for memory)
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2

  # native bin size of the HDF5 is 10 ms → downsample to 100 ms inside srnn_helper.py
  ms_per_sample: 10
  rate_mode: "mean"

  # Footshock input params (still used only to build u, but ignored because use_inputs=false)
  shock_expand_sec: 1.5
  u_scale: 2.0

# ===============================
# Initialization & regularization
# ===============================
initialization:
  warmup_epochs: 700
  lambda_entropy: 1.0e-5
  lambda_usage: 2.0e-2

# ===============================
# Evaluation
# ===============================
evaluation:
  prediction_horizons: [10, 20, 30, 40]

# ===============================
# Optional warm-start from rSLDS
# ===============================
rslds_init:
  path: "/content/drive/MyDrive/RSLDS_SRNN/ModelOutputs/BehaviouralModelrSLDS/Rat{rat_id}/behav_rslds_dropNaN_K3_D1_it12000_z_hat.npy"
  use_head: 500

# ===============================
# Small hyperparameter grid (metadata)
# ===============================
search:
  kappa: [6.0, 8.0, 10.0]    # CHANGED (shifted grid up a bit)
  lr: [1e-3, 5e-4, 1e-4]


