# ===============================
# Experiment configuration: Rat 15 SRNN (with footshock inputs)
# ===============================

experiment:
  name: "rat15_tbptt_w40_s10_k3_inputs_u2_sh1.5"   # << ADDED descriptive suffix
  description: "SRNN (DCA-8, K=3), TBPTT=24, window=40/stride=10; WITH footshock inputs."
  seed: 0
  mode: "with_inputs"     # metadata only

# ===============================
# Data parameters
# ===============================
data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  # << Optional but recommended: save input runs in their own folder
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs/with_inputs"
  subset: "responsive"
  h5_optional: false

# ===============================
# Model parameters
# ===============================
model:
  K_states: 3
  latent_dim: 8
  kappa: 6.0
  use_inputs: true
  name_suffix: "inputs_u2_sh1.5"   # << NEW field for naming runs safely

# ===============================
# Dimensionality reduction
# ===============================
dr:
  method: "dca1"
  n_components: 8
  random_state: 0

# ===============================
# Training configuration
# ===============================
training:
  num_iters: 15000
  window_size: 40
  stride: 10
  tbptt_steps: 24
  batch_size: 256
  lr: 1e-4
  overwrite: false           # << CHANGED to prevent accidental overwrites
  verbose: true
  test_split: 0.2
  ms_per_sample: 1000
  rate_mode: "mean"

  # Footshock input params
  shock_expand_sec: 1.5
  u_scale: 2.0

# ===============================
# Initialization & regularization
# ===============================
initialization:
  warmup_epochs: 700
  lambda_entropy: 1.0e-5
  lambda_usage: 2.0e-2

# ===============================
# Evaluation
# ===============================
evaluation:
  prediction_horizons: [10, 20, 30, 40]

# ===============================
# Optional warm-start from rSLDS
# ===============================
rslds_init:
  path: "/content/drive/My Drive/sRNN/Rat15/initialization for srnn/drop_nan_15000i_z_hat_A.npy"
  use_head: 500

# ===============================
# Small hyperparameter grid
# ===============================
search:
  kappa: [4.0, 6.0, 8.0, 10.0]
  lr: [1e-3, 5e-4, 1e-4]

