# ===============================
# Experiment configuration: Rat 15 SRNN (single-file, selectable mode)
# ===============================

experiment:
  name: "rat15_tbptt_w40_s10_k3"
  description: "SRNN (DCA-8, K=3), TBPTT=24, window=40/stride=10; selectable inputs."
  seed: 0
  # mode is just metadata; you choose at run time via overrides or wrapper
  mode: "unsupervised"     # or "with_inputs"

# ===============================
# Data parameters
# ===============================
data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"                # <- rSLDS root
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: false

  # NOTE:
  # Firing rates will be loaded in this order:
  # 1) If it exists:
  #    /content/drive/MyDrive/RSLDS_SRNN/Downsampled-FiringRates/NpxFiringRate_100msBINSRat15.npy
  #    (true 100 ms binned FR)
  # 2) Otherwise: CSV under Sub-Data/Only-Responsive/... as before.

# ===============================
# Model parameters
# ===============================
model:
  K_states: 3            # fixed
  latent_dim: 8          # fixed
  kappa: 6.0             # you can sweep this later
  use_inputs: false      # <<< UNSUPERVISED: ignore footshocks during training

# ===============================
# Dimensionality reduction
# ===============================
dr:
  method: "dca1"
  n_components: 8
  random_state: 0

# ===============================
# Training configuration
# ===============================
training:
  num_iters: 15000
  window_size: 40
  stride: 10
  tbptt_steps: 24
  batch_size: 256
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2

  # IMPORTANT: native bin size of the FR input
  # For NpxFiringRate_100msBINSRat15.npy, this *is* 100 ms:
  ms_per_sample: 100
  rate_mode: "mean"

  # Footshock input params (only used when model.use_inputs=true)
  shock_expand_sec: 1.5   # temporal support around shocks (in seconds)
  u_scale: 2.0            # (currently unused in code, metadata only)

# ===============================
# Initialization & regularization
# ===============================
initialization:
  warmup_epochs: 700
  lambda_entropy: 1.0e-5   # if state collapse, can increase to 1.0e-4
  lambda_usage: 2.0e-2

# ===============================
# Evaluation
# ===============================
evaluation:
  prediction_horizons: [10, 20, 30, 40]

# ===============================
# Optional warm-start from rSLDS
# ===============================
rslds_init:
  # Template: will become Rat15 automatically in srnn_helper.py
  path: "/content/drive/MyDrive/RSLDS_SRNN/ModelOutputs/BehaviouralModelrSLDS/Rat{rat_id}/behav_rslds_dropNaN_K3_D1_it12000_z_hat.npy"
  use_head: 500

# ===============================
# Small hyperparameter grid (metadata; safe if loader ignores)
# ===============================
search:
  kappa: [4.0, 6.0, 8.0, 10.0]
  lr: [1e-3, 5e-4, 1e-4]

