 # ===============================
# Experiment configuration: Rat 15 SRNN (UNSUPERVISED)
# ===============================

experiment:
  name: "rat15_tbptt_w40_s10_k3_unsup"
  description: "SRNN (DCA-8, K=3), TBPTT=24, window=40/stride=10, NO inputs (fully recurrent/unsupervised)."
  seed: 0

# ===============================
# Data parameters
# ===============================
data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: false

# ===============================
# Model parameters
# ===============================
model:
  K_states: 3
  latent_dim: 8
  kappa: 6.0          # stickiness for smoother transitions
  use_inputs: false   # <-- KEY: disable footshock inputs entirely

# ===============================
# Dimensionality reduction
# ===============================
dr:
  method: "dca1"
  n_components: 8
  random_state: 0

# ===============================
# Training configuration
# ===============================
training:
  num_iters: 15000
  window_size: 40
  stride: 10
  tbptt_steps: 24
  batch_size: 256
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2
  ms_per_sample: 1000
  rate_mode: "mean"

  # Removed shock influence since we're unsupervised:
  # shock_expand_sec: 2.0
  # u_scale: 5.0

# ===============================
# Initialization & regularization
# ===============================
initialization:
  warmup_epochs: 700
  lambda_entropy: 1.0e-5
  lambda_usage: 2.0e-2

# ===============================
# Evaluation
# ===============================
evaluation:
  prediction_horizons: [10, 20, 30, 40]

# ===============================
# Optional warm-start from rSLDS
# ===============================
rslds_init:
  path: "/content/drive/My Drive/sRNN/Rat15/initialization for srnn/drop_nan_15000i_z_hat_A.npy"
  use_head: 300

