experiment:
  name: "rat15_dca1_h8_k3_fast"
  description: "Fast SRNN run with DCA(d=8), K=3."
  seed: 0

data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: true

model:
  K_states: 3
  latent_dim: 8
  kappa: 1.0

dr:
  method: "dca1"
  n_components: 8
  random_state: 0

training:
  num_iters: 1200         # for faster: 600
  window_size: 124        # if 'no batches': use 60
  stride: 18              # if 'no batches': use 10
  batch_size: 256         # if OOM: 128
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2
  ms_per_sample: 1000     # 1000 if using 1 Hz CSV; 10 if using 10 ms CSV
  rate_mode: "mean"

initialization:
  warmup_epochs: 200       # for faster: 100
  lambda_entropy: 1.0e-3
  lambda_usage: 1.0e-2

evaluation:
  prediction_horizons: [10, 20, 30, 40]


