experiment:
  name: "rat16_dca1_h8_k5"
  description: "Train SRNN on Rat16 with DCA(8) and K=5."
  seed: 0

data:
  rat_id: 16
  data_root: "/content/drive/MyDrive/rSLDS"                         # parent of Rat-Data-hdf5 and Sub-Data
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"

model:
  K_states: 3
  latent_dim: 8
  # pick a single kappa for a run OR give multiple and we’ll take the first:
  kappa_values: [0.0, 0.5, 1.0, 2.0]

dr:
  method: "dca1"
  n_components: 8
  random_state: 0

training:
  num_iters: 4000
  window_size: 100
  batch_size: 128
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2

initialization:
  warmup_epochs: 200
  lambda_entropy: 1.0e-3
  lambda_usage: 1.0e-2

evaluation:
  prediction_horizons: [10, 20, 30, 40]

