model:
  K_states: 3
  latent_dim: 8        

dr:
  method: "dca1"
  n_components: 8      
  random_state: 0

training:
  num_iters: 1200        
  window_size: 50        
  stride: 10             
  batch_size: 256        
  lr: 1e-4
  overwrite: true
  verbose: true
  test_split: 0.2
  ms_per_sample: 1000
  rate_mode: "mean"

# IMPORTANT: run only one kappa at a time for speed
model:
  K_states: 3
  latent_dim: 8
  kappa: 1.0           
  # kappa_values: [0.0, 0.5, 1.0, 2.0]   # ← comment out during fast runs
