experiment:
  name: "rat15_srnn_pupil_speed_K2"
  description: "SRNN with 2 discrete states on pupil+speed only"
  seed: 0
  mode: "unsupervised"

data:
  rat_id: 15
  data_root: "/content/drive/MyDrive/rSLDS"
  outputs_root: "/content/drive/MyDrive/sRNN/sRNN-Model-Outputs"
  subset: "responsive"
  h5_optional: false

model:
  K_states: 2            # <<< two discrete states
  latent_dim: 2          # <<< try 1 or 2; both are reasonable
  kappa: 3.0             # self-transition bias for longer dwell times
  use_inputs: true     # <<< ignore shocks during training (purely behavior-driven)
  behavior_only: true    # <<< NEW flag → use pupil+speed as observations

dr:
  method: "pca"          # simple PCA on 2D behavior (can set n_components=2 or 1)
  n_components: 2
  random_state: 0

training:
  num_iters: 1000
  window_size: 50
  stride: 10
  tbptt_steps: 100
  batch_size: 64
  lr: 5e-4
  overwrite: true
  verbose: true
  test_split: 0.0        # keep your “all train” setting
  ms_per_sample: 100
  rate_mode: "mean"

  shock_expand_sec: 0.5
  u_scale: 1.0           # not used when use_inputs: false, but okay to keep

initialization:
  warmup_epochs: 200
  lambda_entropy: 1e-5
  lambda_usage: 5e-3

evaluation:
  prediction_horizons: [10, 20, 30, 40]

rslds_init:
  path: "/content/drive/MyDrive/RSLDS_SRNN/ModelOutputs/BehaviouralModelrSLDS/Rat{rat_id}/behav_rslds_dropNaN_K3_D1_it12000_z_hat.npy"
  use_head: 300
